version: "3.9"
services:
  endpoint_a:
    build: ping-pong
    ports:
      - "1111:1111"
    environment:
      - CLUSTER=AAAA
      - ENDPOINT=1111
  endpoint_b:
    build: ping-pong
    ports:
      - "2222:2222"
    environment:
      - CLUSTER=AAAA
      - ENDPOINT=2222
  endpoint_c:
    build: ping-pong
    ports:
      - "3333:3333"
    environment:
      - CLUSTER=BBBB
      - ENDPOINT=3333
  endpoint_d:
    build: ping-pong
    ports:
      - "4444:4444"
    environment:
      - CLUSTER=BBBB
      - ENDPOINT=3333
  auth:
    build: auth
    ports:
      - "5555:5555"
    environment:
      - PORT=5555
